
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucculvnodabrfwbkzsnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjY3Vsdm5vZGFicmZ3Ymt6c254Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNDQxODksImV4cCI6MjA1NzgyMDE4OX0._tWjZyUAafkMNi5fAOmrgJZu3yuzz_G--S0Wi0qVF1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

/**
 * Utility function to handle Supabase errors in a consistent way
 * @param error The error object from Supabase
 * @param customMessage Optional custom message to display
 * @returns The error object with additional context
 */
export const handleSupabaseError = (error: any, customMessage?: string): Error => {
  console.error("Supabase error:", error);
  
  // Extract the relevant error message
  let errorMessage = "An unexpected error occurred";
  
  if (error?.message) {
    errorMessage = error.message;
  } else if (error?.error_description) {
    errorMessage = error.error_description;
  } else if (error?.details) {
    errorMessage = error.details;
  }
  
  // Use custom message if provided
  if (customMessage) {
    errorMessage = `${customMessage}: ${errorMessage}`;
  }
  
  return new Error(errorMessage);
};
